-- MySQL Script generated by MySQL Workbench
-- Wed Feb 12 16:33:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OrlandoJuniorBaseball
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OrlandoJuniorBaseball
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OrlandoJuniorBaseball` DEFAULT CHARACTER SET utf8 ;
USE `OrlandoJuniorBaseball` ;

-- -----------------------------------------------------
-- Table `OrlandoJuniorBaseball`.`Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrlandoJuniorBaseball`.`Teams` (
  `idTeams` INT NOT NULL AUTO_INCREMENT,
  `team_name` VARCHAR(45) NULL,
  `team_city` VARCHAR(45) NULL,
  `team_manager` VARCHAR(45) NULL,
  PRIMARY KEY (`idTeams`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrlandoJuniorBaseball`.`Coaches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrlandoJuniorBaseball`.`Coaches` (
  `idCoaches` INT NOT NULL AUTO_INCREMENT,
  `coaches_name` VARCHAR(45) NULL,
  `coaches_number` VARCHAR(45) NULL,
  `Teams_idTeams` INT NOT NULL,
  PRIMARY KEY (`idCoaches`),
  INDEX `fk_Coaches_Teams1_idx` (`Teams_idTeams` ASC),
  CONSTRAINT `fk_Coaches_Teams1`
    FOREIGN KEY (`Teams_idTeams`)
    REFERENCES `OrlandoJuniorBaseball`.`Teams` (`idTeams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrlandoJuniorBaseball`.`Players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrlandoJuniorBaseball`.`Players` (
  `idPlayers` INT NOT NULL AUTO_INCREMENT,
  `Players_name` VARCHAR(45) NULL,
  `Players_age` VARCHAR(45) NULL,
  `Players_current` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlayers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrlandoJuniorBaseball`.`Bats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrlandoJuniorBaseball`.`Bats` (
  `idBats` INT NOT NULL AUTO_INCREMENT,
  `Bats_serialnumber` INT NULL,
  `Bats_manufacturer` VARCHAR(45) NULL,
  PRIMARY KEY (`idBats`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrlandoJuniorBaseball`.`Teams_has_Players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrlandoJuniorBaseball`.`Teams_has_Players` (
  `Teams_idTeams` INT NOT NULL,
  `Players_idPlayers` INT NOT NULL,
  `Current_playing` TINYINT NOT NULL,
  PRIMARY KEY (`Teams_idTeams`, `Players_idPlayers`),
  INDEX `fk_Teams_has_Players_Players1_idx` (`Players_idPlayers` ASC),
  INDEX `fk_Teams_has_Players_Teams_idx` (`Teams_idTeams` ASC),
  CONSTRAINT `fk_Teams_has_Players_Teams`
    FOREIGN KEY (`Teams_idTeams`)
    REFERENCES `OrlandoJuniorBaseball`.`Teams` (`idTeams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teams_has_Players_Players1`
    FOREIGN KEY (`Players_idPlayers`)
    REFERENCES `OrlandoJuniorBaseball`.`Players` (`idPlayers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrlandoJuniorBaseball`.`Work_Experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrlandoJuniorBaseball`.`Work_Experience` (
  `idWork_Experience` INT NOT NULL,
  `Experience_name` VARCHAR(45) NULL,
  `Years` INT NOT NULL,
  `Coaches_idCoaches` INT NOT NULL,
  PRIMARY KEY (`idWork_Experience`, `Coaches_idCoaches`),
  INDEX `fk_Work_Experience_Coaches1_idx` (`Coaches_idCoaches` ASC),
  CONSTRAINT `fk_Work_Experience_Coaches1`
    FOREIGN KEY (`Coaches_idCoaches`)
    REFERENCES `OrlandoJuniorBaseball`.`Coaches` (`idCoaches`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrlandoJuniorBaseball`.`Teams_has_Bats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrlandoJuniorBaseball`.`Teams_has_Bats` (
  `Teams_idTeams` INT NOT NULL,
  `Bats_idBats` INT NOT NULL,
  PRIMARY KEY (`Teams_idTeams`, `Bats_idBats`),
  INDEX `fk_Teams_has_Bats_Bats1_idx` (`Bats_idBats` ASC),
  INDEX `fk_Teams_has_Bats_Teams1_idx` (`Teams_idTeams` ASC),
  CONSTRAINT `fk_Teams_has_Bats_Teams1`
    FOREIGN KEY (`Teams_idTeams`)
    REFERENCES `OrlandoJuniorBaseball`.`Teams` (`idTeams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teams_has_Bats_Bats1`
    FOREIGN KEY (`Bats_idBats`)
    REFERENCES `OrlandoJuniorBaseball`.`Bats` (`idBats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
